import test from 'node:test';
import assert from 'node:assert/strict';
import { createPlayerController } from '../src/player/player-controller.js';

function createClock() { let nextId = 1; const timers = new Map(); return { setTimeout(fn, delay) { const id = nextId++; timers.set(id, { fn, delay }); return id; }, clearTimeout(id) { timers.delete(id); }, pending() { return [...timers.entries()].map(([id, value]) => ({ id, ...value })); }, run(id) { const timer = timers.get(id); if (!timer) return; timers.delete(id); timer.fn(); } }; }
function createVideo() { const handlers = new Map(); return { src: '', canPlayType() { return ''; }, addEventListener(name, fn) { handlers.set(name, fn); }, removeEventListener(name) { handlers.delete(name); }, emit(name, event = {}) { handlers.get(name)?.(event); }, pause() {}, load() {}, removeAttribute(name) { if (name === 'src') this.src = ''; } }; }
function createHlsFactory() { const instances = []; function factory() { const handlers = new Map(); const instance = { destroyed: false, attachMedia() {}, loadSource() {}, destroy() { this.destroyed = true; }, on(name, fn) { handlers.set(name, fn); }, off(name) { handlers.delete(name); }, emit(name, data) { handlers.get(name)?.(name, data); } }; instances.push(instance); return instance; } factory.isSupported = () => true; factory.events = { ERROR: 'error' }; factory.instances = instances; return factory; }
const descriptor = { channelId: 'bein-1', manifestUrl: 'https://v2.example/hls/bein-1/index.m3u8' };

test('nonfatal hls errors stay owned by hls.js and do not schedule application recovery', () => { const clock = createClock(); const hlsFactory = createHlsFactory(); const player = createPlayerController({ video: createVideo(), hlsFactory, clock, random: () => 0.5 }); player.load(descriptor); hlsFactory.instances[0].emit('error', { fatal: false, type: 'networkError' }); assert.equal(clock.pending().length, 0); });
test('fatal hls errors schedule only one bounded recovery timer', () => { const clock = createClock(); const hlsFactory = createHlsFactory(); const player = createPlayerController({ video: createVideo(), hlsFactory, clock, random: () => 0.5 }); player.load(descriptor); hlsFactory.instances[0].emit('error', { fatal: true, type: 'networkError' }); hlsFactory.instances[0].emit('error', { fatal: true, type: 'networkError' }); assert.equal(clock.pending().length, 1); assert.equal(clock.pending()[0].delay, 1000); });
test('recovery uses exponential delays capped at ten seconds and stops after four attempts', () => { const clock = createClock(); const hlsFactory = createHlsFactory(); const player = createPlayerController({ video: createVideo(), hlsFactory, clock, random: () => 0.5 }); player.load(descriptor); const observed = []; for (let attempt = 0; attempt < 4; attempt += 1) { hlsFactory.instances.at(-1).emit('error', { fatal: true, type: 'networkError' }); const timer = clock.pending()[0]; observed.push(timer.delay); clock.run(timer.id); } assert.deepEqual(observed, [1000,2000,4000,8000]); hlsFactory.instances.at(-1).emit('error', { fatal: true, type: 'networkError' }); assert.equal(clock.pending().length, 0); assert.equal(player.getState().status, 'ERROR'); });
test('destroy invalidates pending recovery so a stale timer cannot resurrect playback', () => { const clock = createClock(); const hlsFactory = createHlsFactory(); const player = createPlayerController({ video: createVideo(), hlsFactory, clock, random: () => 0.5 }); player.load(descriptor); hlsFactory.instances[0].emit('error', { fatal: true, type: 'networkError' }); const timer = clock.pending()[0]; player.destroy(); const before = hlsFactory.instances.length; clock.run(timer.id); assert.equal(hlsFactory.instances.length, before); assert.equal(player.getState().status, 'STOPPED'); });
